create_clock -name cpu_clk -period 1.55 [get_ports clk]
create_clock -name uart_clk -period 0.96 [get_ports uart_clk]
create_clock -name i2c_clk -period 0.90 [get_ports i2c_clk]
create_clock -name spi_clk -period 0.62 [get_ports spi_clk]
create_clock -name fir_clk -period 1.46 [get_ports fir_clk]

# --- generated clocks (regenerated by gen_clocks.sh) ---

# --- generated clocks (regenerated by gen_clocks.sh) ---

# --- generated clocks (regenerated by gen_clocks.sh) ---

# --- generated clocks (regenerated by gen_clocks.sh) ---
create_generated_clock -name cpu_div2 -source [get_ports clk] \
    -divide_by 2 [get_pins _125495_/Q]
create_generated_clock -name uart_div4 -source [get_ports uart_clk] \
    -divide_by 4 [get_pins _125558_/Q]
create_generated_clock -name i2c_div8 -source [get_ports i2c_clk] \
    -divide_by 8 [get_pins _125627_/Q]
create_generated_clock -name spi_div16 -source [get_ports spi_clk] \
    -divide_by 16 [get_pins _125680_/Q]
create_generated_clock -name fir_div32 -source [get_ports fir_clk] \
    -divide_by 32 [get_pins _125739_/Q]

set_clock_groups -asynchronous \
    -group {cpu_clk cpu_div2} \
    -group {uart_clk uart_div4} \
    -group {i2c_clk i2c_div8} \
    -group {spi_clk spi_div16} \
    -group {fir_clk fir_div32}

set_input_delay  0 -clock cpu_clk  [get_ports {resetn}]
set_input_delay  0 -clock uart_clk [get_ports {uart_rst uart_rxd}]
set_input_delay  0 -clock i2c_clk  [get_ports {i2c_rst scl_pad_i sda_pad_i}]
set_input_delay  0 -clock spi_clk  [get_ports {spi_rst miso_i}]
set_input_delay  0 -clock fir_clk  [get_ports {fir_rst}]

set_output_delay 0 -clock uart_clk [get_ports {uart_txd}]
set_output_delay 0 -clock i2c_clk  [get_ports {scl_pad_o scl_padoen_o sda_pad_o sda_padoen_o}]
set_output_delay 0 -clock spi_clk  [get_ports {sck_o ss_o mosi_o}]
set_output_delay 0 -clock cpu_clk  [get_ports {div_status}]
set_false_path -from [get_ports {resetn uart_rst i2c_rst spi_rst fir_rst}]

