#!/usr/bin/env python3
import sys
from pathlib import Path
sdc   = Path(sys.argv[1])
fresh = Path(sys.argv[2]).read_text().strip()
lines = sdc.read_text().splitlines()
out, i, removed = [], 0, 0
while i < len(lines):
    if lines[i].lstrip().startswith("create_generated_clock"):
        removed += 1
        while i < len(lines) and lines[i].rstrip().endswith("\\"):
            i += 1
        i += 1
        continue
    out.append(lines[i]); i += 1
n = sum(1 for l in fresh.splitlines()
        if l.lstrip().startswith("create_generated_clock"))
idx = next((k for k,l in enumerate(out)
            if l.lstrip().startswith("set_clock_groups")), None)
if idx is None:
    raise SystemExit("no set_clock_groups found - insert manually")
out[idx:idx] = ["# --- generated clocks (regenerated by gen_clocks.sh) ---"] \
               + fresh.splitlines() + [""]
sdc.write_text("\n".join(out) + "\n")
print(f"removed {removed} old block(s); inserted {n} fresh")
